/*
 * Bloq — offline block-based MicroPython IDE
 * Copyright (C) 2026 Benjamin Balga
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import type { BloqPlugin, GenContext } from "../../src/core/types";
import type * as Blockly from "blockly";

// Stepper motors driven over STEP/DIR (A4988, DRV8825, TMC2209 in step/dir
// mode, …), backed by the shipped BloqStepper.py driver. Motion is generated by
// a machine.Timer callback, so every move block returns immediately and the
// motor keeps stepping in the background — a "and wait" move is just a poll on
// is_target_reached(), which adapts to the scheduler exactly like wait_until.
//
// A motor is identified by its STEP pin (the neopixel-by-data-pin idiom), so
// the setup block and the motion blocks agree on one reserved object with no
// variable plumbing for the user.

const COLOUR = 20; // orange-red

const NUM = (n: number) => ({ shadow: { type: "math_number", fields: { NUM: n } } });

/** One reusable Stepper object per STEP pin (created by the setup block). */
function motor(ctx: GenContext, block: Blockly.Block): string {
  return ctx.reserveVariable(`stepper_${block.getFieldValue("STEP")}`);
}

function driver(ctx: GenContext): void {
  ctx.ensureImport("from BloqStepper import Stepper");
  ctx.requireLibrary("/lib/BloqStepper.py");
}

const stepField = {
  type: "field_dropdown",
  name: "STEP",
  options: "$BOARD_OUTPUT_PINS",
};

// Unit dropdowns. The value is the method suffix, so a generator can build the
// call name directly instead of switching on a label.
const POSITION_UNITS = [
  ["steps", ""],
  ["degrees", "_deg"],
  ["turns", "_turns"],
];
const RATE_UNITS = [
  ["steps/s", ""],
  ["degrees/s", "_dps"],
  ["turns/s", "_rps"],
];
const unitField = (name: string, options: string[][]) => ({
  type: "field_dropdown",
  name,
  options,
});

/** Emit a wait-for-idle that adapts to the active codegen mode, like the core
 *  `wait until` block: yield to the scheduler when there is one, else poll. */
function waitUntilIdle(ctx: GenContext, block: Blockly.Block, v: string): void {
  if (ctx.schedulerMode) {
    ctx.line(`yield from sched.wait_until(${v}.is_target_reached)`, block.id);
    ctx.markYield();
  } else {
    ctx.line(`while not ${v}.is_target_reached():`, block.id);
    ctx.indented(() => ctx.line("pass", block.id));
  }
}

export const plugin: BloqPlugin = {
  id: "core-stepper",
  name: "Stepper",
  version: "1.0.0",
  requires: ["gpio"],
  toolbox: { category: "Stepper", colour: COLOUR, order: 95, faIcon: "fa-gears" },

  examples: [
    {
      id: "stepper-shuttle",
      name: "Stepper shuttle",
      description: "Home to an endstop, then run back and forth between two positions",
      file: "stepper-shuttle.bloq",
    },
  ],

  blocks: {
    stepper_setup: {
      kind: "statement",
      json: {
        type: "stepper_setup",
        message0: "set up stepper step %1 dir %2 enable %3 %4 steps per turn %5",
        args0: [
          stepField,
          { type: "field_dropdown", name: "DIR", options: "$BOARD_OUTPUT_PINS" },
          { type: "field_dropdown", name: "EN", options: "$BOARD_OUTPUT_PINS_OR_NONE" },
          { type: "input_dummy" },
          { type: "field_number", name: "SPR", value: 200, min: 1, precision: 1 },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "Create a STEP/DIR stepper. Do this once, before moving it. " +
          "Steps per turn includes microstepping: 200 full steps × 16 microsteps = 3200.",
      },
    },

    stepper_config: {
      kind: "statement",
      json: {
        type: "stepper_config",
        message0: "stepper %1 set speed %2 %3 acceleration %4 %5",
        args0: [
          stepField,
          { type: "input_value", name: "SPEED" },
          unitField("SUNIT", RATE_UNITS),
          { type: "input_value", name: "ACCEL" },
          unitField("AUNIT", [
            ["steps/s²", ""],
            ["degrees/s²", "_dps2"],
            ["turns/s²", "_rps2"],
          ]),
        ],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "Top speed and how fast to ramp up to it. Acceleration 0 means no ramp " +
          "(the motor jumps straight to top speed, which stalls a loaded motor).",
      },
      toolbox: { inputs: { SPEED: NUM(400), ACCEL: NUM(800) } },
    },

    stepper_move: {
      kind: "statement",
      json: {
        type: "stepper_move",
        message0: "stepper %1 %2 %3 %4 %5",
        args0: [
          stepField,
          {
            type: "field_dropdown",
            name: "REL",
            options: [
              ["move to", "target"],
              ["move by", "move"],
            ],
          },
          { type: "input_value", name: "AMOUNT" },
          unitField("UNIT", POSITION_UNITS),
          {
            type: "field_dropdown",
            name: "WAIT",
            options: [
              ["and wait", "1"],
              ["in background", "0"],
            ],
          },
        ],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "Move with a smooth speed ramp. 'move to' is an absolute position, " +
          "'move by' is relative. 'in background' keeps running while the next blocks execute.",
      },
      toolbox: { inputs: { AMOUNT: NUM(200) } },
    },

    stepper_rotate: {
      kind: "statement",
      json: {
        type: "stepper_rotate",
        message0: "stepper %1 rotate %2 at %3 %4",
        args0: [
          stepField,
          {
            type: "field_dropdown",
            name: "DIRECTION",
            options: [
              ["forward", "1"],
              ["backward", "-1"],
            ],
          },
          { type: "input_value", name: "SPEED" },
          unitField("SUNIT", RATE_UNITS),
        ],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "Rotate continuously until stopped (or until a travel limit is reached). " +
          "Runs in the background.",
      },
      toolbox: { inputs: { SPEED: NUM(400) } },
    },

    stepper_stop: {
      kind: "statement",
      json: {
        type: "stepper_stop",
        message0: "stepper %1 %2",
        args0: [
          stepField,
          {
            type: "field_dropdown",
            name: "HOW",
            options: [
              ["stop smoothly", "stop"],
              ["stop now", "hard_stop"],
            ],
          },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "'stop smoothly' ramps down and keeps the position accurate. " +
          "'stop now' halts instantly and will lose steps on a loaded motor.",
      },
    },

    stepper_wait: {
      kind: "statement",
      json: {
        type: "stepper_wait",
        message0: "wait until stepper %1 has stopped",
        args0: [stepField],
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip: "Pause here until a background move finishes.",
      },
    },

    stepper_enable: {
      kind: "statement",
      json: {
        type: "stepper_enable",
        message0: "stepper %1 %2",
        args0: [
          stepField,
          {
            type: "field_dropdown",
            name: "STATE",
            options: [
              ["hold position", "True"],
              ["release (free to turn)", "False"],
            ],
          },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "Energise or release the coils (needs an enable pin). Releasing stops " +
          "the motor drawing current and lets the shaft turn by hand.",
      },
    },

    stepper_set_position: {
      kind: "statement",
      json: {
        type: "stepper_set_position",
        message0: "stepper %1 call current position %2 %3",
        args0: [stepField, { type: "input_value", name: "VALUE" }, unitField("UNIT", POSITION_UNITS)],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip: "Redefine where 'here' is without moving the motor. Usually used to set zero.",
      },
      toolbox: { inputs: { VALUE: NUM(0) } },
    },

    stepper_limits: {
      kind: "statement",
      json: {
        type: "stepper_limits",
        message0: "stepper %1 limit travel from %2 to %3 %4",
        args0: [
          stepField,
          { type: "input_value", name: "MIN" },
          { type: "input_value", name: "MAX" },
          unitField("UNIT", POSITION_UNITS),
        ],
        inputsInline: true,
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "Soft end limits. Moves past them are clamped, and a continuous rotation " +
          "ramps down and stops exactly on the limit.",
      },
      toolbox: { inputs: { MIN: NUM(0), MAX: NUM(2000) } },
    },

    stepper_home: {
      kind: "statement",
      json: {
        type: "stepper_home",
        message0: "stepper %1 home %2 to endstop on pin %3 active %4 at %5 steps/s %6",
        args0: [
          stepField,
          {
            type: "field_dropdown",
            name: "DIRECTION",
            options: [
              ["backward", "-1"],
              ["forward", "1"],
            ],
          },
          { type: "field_dropdown", name: "ENDSTOP", options: "$BOARD_INPUT_PINS" },
          {
            type: "field_dropdown",
            name: "ACTIVE",
            options: [
              ["low", "True"],
              ["high", "False"],
            ],
          },
          { type: "field_number", name: "SPEED", value: 100, min: 1, precision: 1 },
          {
            type: "field_dropdown",
            name: "WAIT",
            options: [
              ["and wait", "1"],
              ["in background", "0"],
            ],
          },
        ],
        previousStatement: null,
        nextStatement: null,
        colour: COLOUR,
        tooltip:
          "Drive slowly until the endstop triggers, then call that position zero. " +
          "'active low' suits a switch wired to ground with a pull-up.",
      },
    },

    stepper_position: {
      kind: "value",
      json: {
        type: "stepper_position",
        message0: "stepper %1 position in %2",
        args0: [stepField, unitField("UNIT", POSITION_UNITS)],
        output: "Number",
        colour: COLOUR,
        tooltip: "Where the motor is now, counted from zero.",
      },
    },

    stepper_is_moving: {
      kind: "value",
      json: {
        type: "stepper_is_moving",
        message0: "stepper %1 is moving?",
        args0: [stepField],
        output: "Boolean",
        colour: COLOUR,
        tooltip: "True while a move or rotation is still running.",
      },
    },

    stepper_measured_speed: {
      kind: "value",
      json: {
        type: "stepper_measured_speed",
        message0: "stepper %1 measured speed (steps/s)",
        args0: [stepField],
        output: "Number",
        colour: COLOUR,
        tooltip:
          "The fastest step rate actually reached during the last move. If this is " +
          "well below the speed you asked for, the board cannot pulse that fast — " +
          "the position is still correct, but the move ran slow. Lower the speed.",
      },
    },
  },

  generators: {
    stepper_setup: (block: Blockly.Block, ctx: GenContext) => {
      driver(ctx);
      ctx.ensureImport("from machine import Pin");
      const en = block.getFieldValue("EN");
      const v = motor(ctx, block);
      // Speed and acceleration are spelled out here (rather than left to the
      // driver defaults) so the code view shows the numbers the motor is using.
      ctx.addSetup(
        `${v} = Stepper(Pin(${block.getFieldValue("STEP")}, Pin.OUT), ` +
          `Pin(${block.getFieldValue("DIR")}, Pin.OUT), ` +
          `${en === "None" ? "None" : `Pin(${en}, Pin.OUT)`}, ` +
          `steps_per_rev=${block.getFieldValue("SPR")}, speed_sps=400, accel_sps2=800)`
      );
    },

    stepper_config: (block: Blockly.Block, ctx: GenContext) => {
      const v = motor(ctx, block);
      ctx.line(`${v}.speed${block.getFieldValue("SUNIT")}(${ctx.value(block, "SPEED", "400")})`, block.id);
      ctx.line(
        `${v}.acceleration${block.getFieldValue("AUNIT")}(${ctx.value(block, "ACCEL", "800")})`,
        block.id
      );
    },

    stepper_move: (block: Blockly.Block, ctx: GenContext) => {
      const v = motor(ctx, block);
      const fn = block.getFieldValue("REL") + block.getFieldValue("UNIT");
      ctx.line(`${v}.${fn}(${ctx.value(block, "AMOUNT", "0")})`, block.id);
      if (block.getFieldValue("WAIT") === "1") waitUntilIdle(ctx, block, v);
    },

    stepper_rotate: (block: Blockly.Block, ctx: GenContext) => {
      const v = motor(ctx, block);
      ctx.line(`${v}.speed${block.getFieldValue("SUNIT")}(${ctx.value(block, "SPEED", "400")})`, block.id);
      ctx.line(`${v}.free_run(${block.getFieldValue("DIRECTION")})`, block.id);
    },

    stepper_stop: (block: Blockly.Block, ctx: GenContext) => {
      ctx.line(`${motor(ctx, block)}.${block.getFieldValue("HOW")}()`, block.id);
    },

    stepper_wait: (block: Blockly.Block, ctx: GenContext) => {
      waitUntilIdle(ctx, block, motor(ctx, block));
    },

    stepper_enable: (block: Blockly.Block, ctx: GenContext) => {
      ctx.line(`${motor(ctx, block)}.enable(${block.getFieldValue("STATE")})`, block.id);
    },

    stepper_set_position: (block: Blockly.Block, ctx: GenContext) => {
      const v = motor(ctx, block);
      ctx.line(
        `${v}.overwrite_pos${block.getFieldValue("UNIT")}(${ctx.value(block, "VALUE", "0")})`,
        block.id
      );
    },

    stepper_limits: (block: Blockly.Block, ctx: GenContext) => {
      const v = motor(ctx, block);
      ctx.line(
        `${v}.set_limits${block.getFieldValue("UNIT")}(${ctx.value(block, "MIN", "0")}, ` +
          `${ctx.value(block, "MAX", "0")})`,
        block.id
      );
    },

    stepper_home: (block: Blockly.Block, ctx: GenContext) => {
      const v = motor(ctx, block);
      ctx.ensureImport("from machine import Pin");
      ctx.line(
        `${v}.home(Pin(${block.getFieldValue("ENDSTOP")}, Pin.IN, Pin.PULL_UP), ` +
          `direction=${block.getFieldValue("DIRECTION")}, ` +
          `speed_sps=${block.getFieldValue("SPEED")}, ` +
          `active_low=${block.getFieldValue("ACTIVE")})`,
        block.id
      );
      if (block.getFieldValue("WAIT") === "1") waitUntilIdle(ctx, block, v);
    },

    stepper_position: (block: Blockly.Block, ctx: GenContext) =>
      `${motor(ctx, block)}.get_pos${block.getFieldValue("UNIT")}()`,

    stepper_is_moving: (block: Blockly.Block, ctx: GenContext) => `${motor(ctx, block)}.is_moving()`,

    stepper_measured_speed: (block: Blockly.Block, ctx: GenContext) =>
      `${motor(ctx, block)}.achieved_sps()`,
  },
};
