import * as Blockly from "blockly";
import type {
  Board,
  BlockDef,
  BlockGenerator,
  ValueGenerator,
  GenContext,
  GenResult,
} from "./types";
import { blockDefsFor, generatorsFor } from "./registry";

interface LineRecord {
  text: string;
  blockId?: string;
}

const INDENT = "    ";

/**
 * Translates a Blockly workspace to MicroPython.
 *
 * Two modes, chosen automatically:
 *  - simple:    <=1 hat and no block requires the scheduler. Plain linear code,
 *               no runtime import — readable, ~1:1 with the blocks.
 *  - scheduler: >1 hat OR a block explicitly requires it. Each hat becomes a
 *               cooperative generator run by mbruntime's round-robin scheduler.
 */
export class CodeGen {
  private board: Board;
  private defs: Map<string, BlockDef>;
  private gens: Map<string, BlockGenerator | ValueGenerator>;

  constructor(
    board: Board,
    // Injectable for headless testing; defaults to the plugin registry.
    opts?: {
      defs?: Map<string, BlockDef>;
      gens?: Map<string, BlockGenerator | ValueGenerator>;
    }
  ) {
    this.board = board;
    this.defs = opts?.defs ?? blockDefsFor(board);
    this.gens = opts?.gens ?? generatorsFor(board);
  }

  generate(workspace: Blockly.Workspace): GenResult {
    const hats = workspace
      .getTopBlocks(true)
      .filter((b) => this.defs.get(b.type)?.hat);

    const schedulerMode = this.decideSchedulerMode(workspace, hats);

    // Header buckets, populated as generators run.
    const imports = new Set<string>(this.board.runtime.imports);
    const setup: string[] = [];
    const setupSeen = new Set<string>();
    const functions = new Map<string, string>();
    const requiredLibraries = new Set<string>();
    const varNames = new Map<string, string>();

    // Generate each hat body into its own buffer.
    const stacks = hats.map((hat) => {
      const buf: LineRecord[] = [];
      let hasYield = false;
      const ctx = this.makeContext({
        schedulerMode,
        imports,
        setup,
        setupSeen,
        functions,
        requiredLibraries,
        varNames,
        buf,
        onYield: () => (hasYield = true),
      });
      this.genChain(hat.getNextBlock(), ctx);
      return { hat, buf, hasYield };
    });

    if (schedulerMode) requiredLibraries.add("/lib/mbruntime.py");

    // ---- Assemble ordered output ----
    const out: LineRecord[] = [];
    out.push({ text: "# Generated by Microblock — editing detaches from blocks" });
    for (const imp of [...imports].sort()) out.push({ text: imp });
    if (schedulerMode) out.push({ text: "from mbruntime import sched" });
    out.push({ text: "" });

    for (const s of setup) out.push({ text: s });
    if (setup.length) out.push({ text: "" });

    for (const [name, body] of functions) {
      out.push({ text: `def ${name}:` });
      for (const ln of body.split("\n")) out.push({ text: INDENT + ln });
      out.push({ text: "" });
    }

    if (!schedulerMode) {
      // At most one stack; emit its body at top level.
      const body = stacks[0]?.buf ?? [];
      if (body.length === 0) out.push({ text: "# (empty program)" });
      out.push(...body);
    } else {
      stacks.forEach((s, i) => {
        out.push({ text: `def stack_${i + 1}():`, blockId: s.hat.id });
        if (s.buf.length === 0) {
          out.push({ text: INDENT + "yield", blockId: s.hat.id });
        } else {
          for (const rec of s.buf) out.push({ text: INDENT + rec.text, blockId: rec.blockId });
          // A generator needs at least one yield; a hat with no loop/wait has none.
          if (!s.hasYield) out.push({ text: INDENT + "yield", blockId: s.hat.id });
        }
        out.push({ text: "" });
      });
      stacks.forEach((_, i) => out.push({ text: `sched.spawn(stack_${i + 1})` }));
      out.push({ text: "sched.run()" });
    }

    // ---- Build source maps ----
    const lineToBlock = new Map<number, string>();
    const blockToLines = new Map<string, number[]>();
    out.forEach((rec, idx) => {
      const line = idx + 1; // 1-based, matches device tracebacks
      if (rec.blockId) {
        lineToBlock.set(line, rec.blockId);
        const arr = blockToLines.get(rec.blockId) ?? [];
        arr.push(line);
        blockToLines.set(rec.blockId, arr);
      }
    });

    return {
      code: out.map((r) => r.text).join("\n") + "\n",
      lineToBlock,
      blockToLines,
      requiredLibraries,
      schedulerMode,
    };
  }

  private decideSchedulerMode(workspace: Blockly.Workspace, hats: Blockly.Block[]): boolean {
    if (hats.length > 1) return true;
    return workspace
      .getAllBlocks(false)
      .some((b) => this.defs.get(b.type)?.requiresScheduler);
  }

  /** Walk a statement chain (block + its `next` siblings), dispatching generators. */
  private genChain(first: Blockly.Block | null, ctx: GenContext): void {
    let b = first;
    while (b) {
      if (!b.isEnabled?.()) {
        b = b.getNextBlock();
        continue;
      }
      this.dispatch(b, ctx);
      b = b.getNextBlock();
    }
  }

  private dispatch(block: Blockly.Block, ctx: GenContext): void {
    // Board override wins over the plugin generator (dialect remapping).
    const override = this.board.overrides?.[block.type];
    if (override) {
      for (const imp of override.imports ?? []) ctx.ensureImport(imp);
      ctx.line(applyTemplate(override.template, block), block.id);
      return;
    }
    const gen = this.gens.get(block.type);
    if (!gen) {
      ctx.line(`# [unknown block: ${block.type}]`, block.id);
      return;
    }
    if (typeof gen === "string") {
      ctx.line(applyTemplate(gen, block), block.id);
    } else {
      (gen as BlockGenerator as (b: Blockly.Block, c: GenContext) => void)(block, ctx);
    }
  }

  private evalValue(block: Blockly.Block, inputName: string, fallback: string, ctx: GenContext): string {
    const target = block.getInputTargetBlock(inputName);
    if (!target) return fallback;
    const gen = this.gens.get(target.type);
    if (typeof gen === "string") return applyTemplate(gen, target);
    if (typeof gen === "function") {
      return (gen as ValueGenerator)(target, ctx) || fallback;
    }
    return fallback;
  }

  private makeContext(s: {
    schedulerMode: boolean;
    imports: Set<string>;
    setup: string[];
    setupSeen: Set<string>;
    functions: Map<string, string>;
    requiredLibraries: Set<string>;
    varNames: Map<string, string>;
    buf: LineRecord[];
    onYield: () => void;
  }): GenContext {
    let indent = 0;
    const ctx: GenContext = {
      schedulerMode: s.schedulerMode,
      board: this.board,
      ensureImport: (line) => s.imports.add(line),
      addSetup: (line) => {
        if (!s.setupSeen.has(line)) {
          s.setupSeen.add(line);
          s.setup.push(line);
        }
      },
      defineFunction: (name, body) => s.functions.set(name, body),
      requireLibrary: (dest) => s.requiredLibraries.add(dest),
      reserveVariable: (base) => {
        // Idempotent per base: same logical resource -> same variable name.
        const key = sanitize(base);
        const existing = s.varNames.get(key);
        if (existing) return existing;
        let name = key;
        let n = 2;
        const used = new Set(s.varNames.values());
        while (used.has(name)) name = `${key}${n++}`;
        s.varNames.set(key, name);
        return name;
      },
      line: (text, blockId) => s.buf.push({ text: INDENT.repeat(indent) + text, blockId }),
      indented: (fn) => {
        indent++;
        try {
          fn();
        } finally {
          indent--;
        }
      },
      statement: (block, inputName) => this.genChain(block.getInputTargetBlock(inputName), ctx),
      value: (block, inputName, fallback = "0") => this.evalValue(block, inputName, fallback, ctx),
      markYield: () => s.onYield(),
      linesEmitted: () => s.buf.length,
    };
    return ctx;
  }
}

function sanitize(base: string): string {
  const s = base.replace(/[^a-zA-Z0-9_]/g, "_");
  return /^[a-zA-Z_]/.test(s) ? s : `_${s}`;
}

/** Replace {FIELD} placeholders with the block's field values (Tier A templates). */
function applyTemplate(template: string, block: Blockly.Block): string {
  return template.replace(/\{(\w+)\}/g, (_, name) => {
    const v = block.getFieldValue(name);
    return v == null ? "" : String(v);
  });
}
